name: Test conda
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/conda.yml'
  workflow_dispatch:
jobs:
  check:
    runs-on: ${{ matrix.config.os }}
    name: test-${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-11}
          - {os: ubuntu-20.04}
    steps:
      - uses: actions/checkout@v2
      - name: Where?
        run: which conda
      - name: Information
        run: conda info
      - name: Configuration
        run: |
          conda config --show-sources
          conda config --show
      - name: initialize
        run: conda init
      - name: Is conda a function or file?
        run: type conda
      - name: Is conda a function or file? 2
        run: type conda
        shell: bash -l {0}
      - name: Is conda a function or file? 3
        run: |
          grep conda ~/.bashrc
          source ~/.bashrc
          type conda
        shell: bash -l {0}
      - name: conda-lock
        run: conda install -c conda-forge conda-lock
