name: Test conda
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/conda.yml'
  workflow_dispatch:
defaults:
  run:
    shell: bash -l {0}
jobs:
  conda:
    runs-on: ${{ matrix.config.os }}
    name: test-${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-11, slug: 'macos'}
          - {os: ubuntu-20.04, slug: 'linux'}
          - {os: windows-latest, slug: 'win'}
    env:
      lockfile: ci/environment-${{ matrix.config.slug }}.lock
      _R_CHECK_CRAN_INCOMING_: TRUE
      _R_CHECK_CRAN_INCOMING_REMOTE_: FALSE
      TZ: UTC
    steps:
      - uses: actions/checkout@v2
        with:
          path: ci
      - uses: actions/checkout@v2
        with:
          repository: workflowr/workflowr
          path: workflowr
      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ${{ env.lockfile }}
          environment-name: wflow-env
          cache-env: true
          cache-env-key: ${{ runner.os }}-${{ hashFiles(env.lockfile) }}-0
          # Install qpdf (not available for Windows)
          extra-specs: |
            sel(linux): conda-forge::qpdf
            sel(osx): conda-forge::qpdf
      - name: Session information
        run: Rscript -e "sessionInfo()"
      - name: Build
        run: R CMD build --no-manual workflowr/
      - name: Check
        run: R CMD check --no-manual --no-tests --as-cran workflowr_*.tar.gz
