name: Test conda
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/conda.yml'
      - 'environment.yml'
  workflow_dispatch:
defaults:
  run:
    shell: bash -l {0}
jobs:
  conda:
    runs-on: ${{ matrix.config.os }}
    name: test-${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-11, slug: 'macos'}
          - {os: ubuntu-20.04, slug: 'linux'}
          - {os: windows-latest, slug: 'win'}
    env:
      lockfile: environment-${{ matrix.config.slug }}.lock
    steps:
      - uses: actions/checkout@v2
      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ${{ env.lockfile }}
          environment-name: wflow-env
          cache-env: true
          cache-env-key: ${{ runner.os }}-${{ hashFiles(env.lockfile) }}-0
      - name: Where?
        run: |
          which micromamba
          which python
          which Rscript
      - name: Install workflowr
        run: Rscript -e 'print(.libPaths()); install.packages("workflowr", dependencies = FALSE)'
      - name: Install workflowr
        run: |
          print(.libPaths())
          library("workflowr")
          sessionInfo()
        shell: bash -l -c Rscript {0}
