name: Export lockfile per OS
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/lockfile.yml'
  workflow_dispatch:
defaults:
  run:
    shell: bash -l {0}
jobs:
  check:
    runs-on: ${{ matrix.config.os }}
    name: lock-${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-11, slug: 'macos'}
          - {os: ubuntu-20.04, slug: 'linux'}
          - {os: windows-latest, slug: 'win'}
    steps:
      - uses: actions/checkout@v2
      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
      - name: Export lockfile
        run: conda list --explicit > environment-${{ matrix.config.slug }}.lock
      - name: Commit lockfile
        run: |
          git config --local user.name "GitHub Actions"
          git pull origin main
          git add environment-${{ matrix.config.slug }}.lock
          git commit --allow-empty -m "Update lockfile for ${{ matrix.config.slug }}"
          git push origin main
